services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: temp_rails
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - .:/app
    environment:
      - TZ=Asia/Tokyo
    tty: true
    stdin_open: true
    ports:
      - 3001:3001
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: temp_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=default
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
      - ./docker/db/init:/docker-entrypoint-initdb.d
