services:
  backend:
    build:
      context: ./docker/backend
      dockerfile: Dockerfile
    volumes:
      - .:/go/src/app
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    container_name: go-backend-db

  db:
    image: mysql:8.0
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=default
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=secret
      - TZ=Asia/Tokyo
    container_name: db-backend-go
