version: "3.8"
volumes:
  php-fpm-socket:
services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - app
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - php-fpm-socket:/var/run/php-fpm
      - .:/var/www/html
    container_name: web

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - db
    volumes:
      - ./docker/app/php.ini:/usr/local/etc/php/php.ini
      - php-fpm-socket:/var/run/php-fpm
      - .:/var/www/html
    container_name: app

  db:
    image: mysql:8.0
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    container_name: db
